version: '3'

services:

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./configs:/etc/velocore/"
      - "./:/velocore/"
    command: "python velo_core/main.py"

  db:
    image: postgres:11.4
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: velocore
      POSTGRES_DB: velo_core_db

#
#  redis:
#    image: "redis:alpine"